steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/hello-repo/cicd-nodejs:1.0', '.']
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/hello-repo/cicd-nodejs:1.0']
  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['rollout', 'restart', 'deployment', 'helloworld-gke']
    env:
      - CLOUDSDK_CONTAINER_CLUSTER=cluster-us-central1-nodejs
      - CLOUDSDK_COMPUTE_ZONE=us-central1-a
      - CLOUDSDK_COMPUTE_REGION=us-central1
options:
  logging: CLOUD_LOGGING_ONLY
  